CREATE TABLE GAMES_T (
    GAME_ID INT AUTO_INCREMENT,
    USER_ID VARCHAR(256) NOT NULL,
    CARDS TEXT NOT NULL,
    TURNS INT NOT NULL,
    INSDATE DATETIME NOT NULL,
    UPDDATE DATETIME NOT NULL,
);