CREATE TABLE GAMES_T (
    GAME_ID INT AUTO_INCREMENT,
    USER_ID VARCHAR(256) NOT NULL,
    GAME_LEVEL VARCHAR(256) NOT NULL,
    TURNS INT NOT NULL,
    FIRST_CARD_INDEX INT,
    INSDATE DATETIME NOT NULL,
    UPDDATE DATETIME NOT NULL,
    PRIMARY KEY (GAME_ID)
);